# Generated by Django 5.2.3 on 2025-06-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_brands_alter_car_brand_delete_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
